services:
  - type: web
    name: proxy-checker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proxy-checker-db
          property: connectionString
    plan: free

databases:
  - name: proxy-checker-db
    plan: free
    ipAllowList:
      - 0.0.0.0/0